create table if not exists public.reviews (
 id bigint generated by default as identity primary key,
 name text not null check (char_length(name) between 1 and 40),
 review text not null check (char_length(review) between 1 and 240),
 photo_url text,
 rating smallint not null default 5 check (rating between 1 and 5),
 approved boolean not null default false,
 created_at timestamptz not null default now()
);
alter table public.reviews enable row level security;
alter table public.reviews add column if not exists photo_url text;
alter table public.reviews add column if not exists rating smallint not null default 5;
alter table public.reviews drop constraint if exists reviews_rating_check;
alter table public.reviews add constraint reviews_rating_check check (rating between 1 and 5);
alter table public.reviews alter column approved set default false;
alter table public.reviews alter column created_at set default now();
drop policy if exists "Anyone can submit reviews" on public.reviews;
drop policy if exists "Anyone can read approved reviews" on public.reviews;
drop policy if exists "Public can submit unapproved reviews" on public.reviews;
drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can submit unapproved reviews" on public.reviews for insert to anon, authenticated with check (approved = false and rating between 1 and 5);
create policy "Public can read approved reviews" on public.reviews for select to anon, authenticated using (approved = true);

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('review-photos','review-photos',true,5242880,array['image/*'])
on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/*'];
drop policy if exists "Public can upload review photos" on storage.objects;
drop policy if exists "Public can view review photos" on storage.objects;
create policy "Public can upload review photos" on storage.objects for insert to anon, authenticated with check (bucket_id='review-photos');
create policy "Public can view review photos" on storage.objects for select to anon, authenticated using (bucket_id='review-photos');
revoke update, delete on public.reviews from anon, authenticated;
revoke update, delete on storage.objects from anon, authenticated;
-- Moderate in Supabase Table Editor. Never expose the service_role key in the frontend.
